// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5CQBjV4AUAL5OWSGkvmnI00ncvkKsxys',
    appId: '1:887199560885:web:24a72050fab1155d1d3afc',
    messagingSenderId: '887199560885',
    projectId: 'flutter-auth-594d4',
    authDomain: 'flutter-auth-594d4.firebaseapp.com',
    storageBucket: 'flutter-auth-594d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0bP8B8irxKPmZHfmjguYHvMwc1H5aMb4',
    appId: '1:887199560885:android:e50fe03bbe92ae4b1d3afc',
    messagingSenderId: '887199560885',
    projectId: 'flutter-auth-594d4',
    storageBucket: 'flutter-auth-594d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAdNk46yQGgZSjz2XSpDmzNGy1Urw-G64',
    appId: '1:887199560885:ios:884abfd46a3819a41d3afc',
    messagingSenderId: '887199560885',
    projectId: 'flutter-auth-594d4',
    storageBucket: 'flutter-auth-594d4.appspot.com',
    iosClientId: '887199560885-d52c5vrapa69lblvshmmahsdpngj7qsn.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAdNk46yQGgZSjz2XSpDmzNGy1Urw-G64',
    appId: '1:887199560885:ios:884abfd46a3819a41d3afc',
    messagingSenderId: '887199560885',
    projectId: 'flutter-auth-594d4',
    storageBucket: 'flutter-auth-594d4.appspot.com',
    iosClientId: '887199560885-d52c5vrapa69lblvshmmahsdpngj7qsn.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginUi',
  );
}
